# Generated by Django 3.0.2 on 2020-03-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageApp', '0002_roominfo_roompass'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='CurFee',
            field=models.FloatField(default=0),
        ),
    ]
